name: Build Redis 8.4.0 (aarch64)
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装交叉编译工具链
        run: |
          sudo apt update && sudo apt install -y \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          build-essential \
          make \
          binutils-aarch64-linux-gnu

      - name: 清理旧产物
        run: |
          make distclean
          CC=aarch64-linux-gnu-gcc \
          CXX=aarch64-linux-gnu-g++ \
          EXTRA_CFLAGS="-march=armv8-a -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wl,--rpath=/usr/aarch64-linux-gnu/lib" \
          EXTRA_LDFLAGS="-L/usr/aarch64-linux-gnu/lib -static-libgcc -Wl,--version-script=/dev/null -Wl,--undefined-version" \
          make -j2 MALLOC=libc all

      - name: 验证产物
        run: |
          ls -l src/redis-*
          file src/redis-server
          file src/redis-cli
          file src/redis-benchmark
          aarch64-linux-gnu-readelf -s src/redis-server | grep GLIBC_ | awk '{print $8}' | sort -u | grep -E '^GLIBC_'

      - name: 上传全套编译产物
        uses: actions/upload-artifact@v4
        with:
          name: redis-8.4.0-aarch64-full-glibc2.28
          path: |
            src/redis-server
            src/redis-cli
            src/redis-benchmark
            src/redis-sentinel
            src/redis-check-rdb
            src/redis-check-aof
